# Test API
@username={{$dotenv USER_NAME}}
@email={{$dotenv USER_EMAIL}}
@password={{$dotenv USER_PASSWORD}}
@usernameupdate={{$dotenv USER_UPDATE}}
@Content-Type={{$dotenv CONTENT_TYPE}}
@tokenkey={{$dotenv TOKEN}}
@linkpost_Registeraccount={{$dotenv LINKPOST_RET}}
@linkget_alluser={{$dotenv LINKGET_ALLUSER}}
@linkpost_authen_login={{$dotenv LINKPOST_AUTHEN}}
@linkget_profile={{$dotenv LINGET_PROFILE}}
@linkput_update={{$dotenv LINKPUT_UPDATE}}

### Identification Register account
POST  {{linkpost_Registeraccount}}
Content-Type: {{Content-Type}}

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}"
}


### Get all users
GET {{linkget_alluser}}
Content-Type: {{Content-Type}}

### Authentication / Login
POST  {{linkpost_authen_login}}
Content-Type: {{Content-Type}}

{
    "identifier": "{{email}}",
    "password": "{{password}}"
}

### Get profile
GET {{linkget_profile}}
Content-Type: {{Content-Type}}
Authorization: {{tokenkey}}

### Update profile
PUT {{linkput_update}}
Content-Type: {{Content-Type}}
Authorization: {{tokenkey}}

{
    "username": "{{usernameupdate}}"
}