# Test API
@username={{$env USER_NAME}}
@email={{$env USER_EMAIL}}
@password={{$env USER_PASSWORD}}
@usernameupdate={{$env USER_UPDATE}}
@Content-Type={{$env CONTENT_TYPE}}
@tokenkey={{$env TOKEN}}
@linkpost_Registeraccount={{$env LINKPOST_RET}}
@linkget_alluser={{$env LINKGET_ALLUSER}}
@linkpost_authen_login={{$env LINKPOST_AUTHEN}}
@linkget_profile={{$env LINGET_PROFILE}}
@linkput_update={{$env LINKPUT_UPDATE}}

### Identification Register account
POST  {{linkpost_Registeraccount}}
Content-Type: {{Content-Type}}

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}"
}


### Get all users
GET {{linkget_alluser}}
Content-Type: {{Content-Type}}

### Authentication / Login
POST  {{linkpost_authen_login}}
Content-Type: {{Content-Type}}

{
    "identifier": "{{email}}",
    "password": "{{password}}"
}

### Get profile
GET {{linkget_profile}}
Content-Type: {{Content-Type}}
Authorization: {{tokenkey}}

### Update profile
PUT {{linkput_update}}
Content-Type: {{Content-Type}}
Authorization: {{tokenkey}}

{
    "username": "{{usernameupdate}}"
}