services:
  db: 
   image: postgres:latest
   container_name: my_db_compose
   ports:
    - "55432:5432"
   environment:
    - POSTGRES_DB=kanit
    - POSTGRES_USER=kanit
    - POSTGRES_PASSWORD=kanit
