services:
  db: 
   image: postgres:latest
   container_name: my_db_compose
   ports:
    - "50001:5432"
   environment:
    - POSTGRES_DB=${DATABASE_NAME}
    - POSTGRES_USER=${DATABASE_USERNAME}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  app:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "8080:1337"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
