services:
  db: 
   image: ${IMAGE_DB}
   container_name: ${CONTAINER_DB}
   ports:
    - "${DATABASE_PORT}"
   environment:
    - POSTGRES_DB=${DATABASE_NAME}
    - POSTGRES_USER=${DATABASE_USERNAME}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  app:
    image: ${APP_IMAGE}
    container_name: ${APP_CONTAINER}
    ports:
      - "${APP_PORT}"
    environment:
      - DATABASE_HOST=${APP_DB_HOST}
      - DATABASE_PORT=${APP_PORT_IN}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
