services:
  db: 
   image: postgres:latest
   container_name: my_db_compose
   ports:
    - "50001:5432"
   environment:
    - POSTGRES_DB=kanit
    - POSTGRES_USER=kanit
    - POSTGRES_PASSWORD=kanit

  app:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "8080:1337"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=kanit
      - DATABASE_USERNAME=kanit
      - DATABASE_PASSWORD=kanit
